# Generated by Django 2.1.4 on 2019-01-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apPaterno', models.CharField(max_length=30)),
                ('apMaterno', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('direccion', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=False)),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('latitud', models.CharField(max_length=25)),
                ('longitud', models.CharField(max_length=25)),
            ],
        ),
    ]
