# Generated by Django 2.1.5 on 2019-01-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
