# Generated by Django 2.1.4 on 2019-01-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('creado', 'Creado'), ('aprobado', 'Aprobado'), ('salida', 'Salida de caja'), ('por cobrar', 'Por cobrar'), ('cobrado', 'Cobrado')], max_length=10),
        ),
    ]
