# Generated by Django 2.1.4 on 2019-01-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0002_auto_20190115_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('1', 'Creado'), ('2', 'Aprobado'), ('3', 'Salida de caja'), ('4', 'Por cobrar'), ('5', 'Cobrado')], default='1', max_length=10),
        ),
    ]
